[package]
name = "rust-simple-var"
version = "0.1.0"
edition = "2021"

[dependencies]
blas-src = { version = "0.10.0" }
ndarray = { version = "0.15.6", features = ["blas"] }
ndarray-linalg = { version = "0.16.0" }
rand = "0.8.5"
tracing = "0.1.41"
